### ISSUE TITLE
Request: media player full album art

### ISSUE THREAD

**Issue by Tedsterh** [DBuit/Homekit-panel-card#31]
Would it be possible to have the currently playing song art fill the card instead of the white background, maybe this could be an additional setting?

**Comment by DBuit** [comment]
Hi @Tedsterh it is possible but maybe it can already be done.

There are some nice media player card like https://community.home-assistant.io/t/lovelace-mini-media-player/68459 or default https://www.home-assistant.io/lovelace/media-control/ which show the album art.

So you could use the card as a tile function: https://github.com/DBuit/Homekit-panel-card#custom-card-as-a-tile

And load another lovelace card in a tile, overwrite some styles to make it fit. More people have done it

**Comment by Tedsterh** [comment]
Hi @DBuit I haven't used CSS before and I'm not sure where to start. Is there anyway of setting the height of the card to fill the parent card? At the minute it is only filling half the tile? I am using the mini-media-player inside a 1x2 tile.

**Comment by DBuit** [comment]
Hi @Tedsterh 

you could try this:
```
                         - card: media-control
                            wider: true
                            higher: true
                            noPadding: true
                            cardOptions:
                              entity: media_player.keuken
                            cardStyle: |
                              ha-card {
                                height:100%;
                              }
                              .ratio {
                                padding-bottom: 70%!important;
                              }
```

**Comment by Tedsterh** [comment]
This works really well and I love the way it looks. Is there anyway to set the press and hold action to popup the media_player-popup-card so I can use the vertical slider for volume?

**Comment by DBuit** [comment]
Hi @Tedsterh ,

You cant use the popup from the homekit card because when you use the longpress action it won't trigger my card but it triggers the media-control card.

But what you can do is use browser_mod this component has `popup_cards:` that you can use to overwrite the default pop-up with a custom pop-up with the vertical volume slider.

**Comment by Freshhat** [comment]
Thanks, this is also working on my side. I only added additional stuff for the Title (current playing song) because the album art was overlaying that text:

`                cardStyle: |
                  ha-card {
                    height: 100%;
                  }
                  .ratio {
                    padding-bottom: 70%!important;
                  }
                  .title-controls {
                    width: 100%;
                    height: 100%;
                  }`

Now everything is displayed in a correct way on my side:

![image](https://user-images.githubusercontent.com/18122096/81394170-d1eadd80-9121-11ea-87cb-dcf7f12c4f7a.png)

**Comment by filikun** [comment]
I can't get this to work. By default with no CCS and default media card it looks like this. Tried adding CSS to it but would not get it. Any idea?
![image](https://user-images.githubusercontent.com/9947929/119242029-f104b380-bb5a-11eb-977c-f970d8d52608.png)

**Comment by Twours** [comment]
Hi, 

Thank you for all this! Was exactly what I was looking for. It seems I can't change the name or the icon in the cadoption. How would I add an icon?
